package fpt.qn.mes.audit.domain.entities;

public enum AuditAction {
    CREATE_WORK_ORDER,
    RESERVE_MATERIAL,
    RELEASE_RESERVATION,
    START_PRODUCTION,
    PAUSE_PRODUCTION,
    RESUME_PRODUCTION,
    COMPLETE_PRODUCTION,
    QC_PASS,
    QC_FAIL,
    QC_HOLD,
    QC_RELEASE,
    SCRAP_STOCK,
    CREATE_MAINTENANCE_TICKET,
    START_MAINTENANCE,
    RESOLVE_MAINTENANCE_TICKET,
    CANCEL_MAINTENANCE_TICKET,
    CLOSE_MAINTENANCE_TICKET,
    ADJUST_STOCK,
    ACTIVATE_BOM
}
