package fpt.qn.mes.audit.domain.entities;

public enum AuditAction {
    CREATE_WORK_ORDER, UPDATE_WORK_ORDER, CANCEL_WORK_ORDER,
    RESERVE_MATERIAL, RELEASE_RESERVATION, START_PRODUCTION,
    PAUSE_PRODUCTION, RESUME_PRODUCTION, COMPLETE_PRODUCTION,
    CREATE_INSPECTION, QC_PASS, QC_FAIL, QC_HOLD, QC_RELEASE, SCRAP_STOCK,
    CREATE_MAINTENANCE_TICKET, START_MAINTENANCE, RESOLVE_MAINTENANCE_TICKET,
    CANCEL_MAINTENANCE_TICKET, CLOSE_MAINTENANCE_TICKET,
    RECORD_STOCK_IN, ADJUST_STOCK,
    CREATE_BOM, ACTIVATE_BOM, DEACTIVATE_BOM,
    CREATE_USER, UPDATE_USER, ACTIVATE_USER, DEACTIVATE_USER,
    CREATE_PRODUCT, UPDATE_PRODUCT, ACTIVATE_PRODUCT, DEACTIVATE_PRODUCT,
    CREATE_MACHINE, UPDATE_MACHINE, CHANGE_MACHINE_STATUS,
    CREATE_LINE, UPDATE_LINE, ACTIVATE_LINE, DEACTIVATE_LINE,
    CREATE_WAREHOUSE, UPDATE_WAREHOUSE, ACTIVATE_WAREHOUSE, DEACTIVATE_WAREHOUSE,
    ASSIGN_WAREHOUSE_MANAGER, REMOVE_WAREHOUSE_MANAGER,
    CREATE_LOCATION, UPDATE_LOCATION, ACTIVATE_LOCATION, DEACTIVATE_LOCATION
}
