---
spring:
  application:
    name: project-management-system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mes}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jooq:
    sql-dialect: POSTGRES
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
app:
  jwt:
    secret: ${JWT_SECRET:k8wT5KF1ZrFojvpXJbhXOcYVv44lCKvOwQudCRY6HjxxTGH3WQbQDHEFZjhS+mCE}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}     # 15 minutes
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging:
  level:
    fpt.qn.mes: DEBUG
    org.springframework.security: INFO
